### PR TITLE
Add cities to search filter

### LINKED ISSUE #30: Add filter for Cities
> Add Cities 
> mirror the list on the front page

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?
Add cities to search filter.

### Internal
Use a new app for local static data, for example cities, and later data types as well
use a templatetag to make the data available for templates.
Maybe we need to update the ansible script @kalxas 

### Screenshot
bildschirmfoto 2017-08-28 um 17 59 10

### Related Issue
closes #30

### CODE REVIEW

**Comment by kalxas** [comment]
The list of cities has a "Type" label

**Comment by kalxas** [comment]
screenshot_20170831_235026

**Comment by milafrerichs** [comment]
yes, we need to add stuff to transifex. 
I don't know where that is.

**Comment by kalxas** [comment]
Superseded by #75

**Pull request closed without merging**
