### PR TITLE
Move searchbar to the header instead of the sidebar

### LINKED ISSUE #26: Big Search bar
Request via Google Doc:
> Remove Text filter and make the big “Search” area actually searchable

bildschirmfoto 2017-08-24 um 14 52 47

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?
Move searchbar to header, see screenshot
requested to move the text Search in the header for easier access and to
replicate the CKAN search
### Screenshot
bildschirmfoto 2017-08-24 um 17 19 10
bildschirmfoto 2017-08-24 um 17 27 21

### Related Issue
closes #26

### CODE REVIEW

**Comment by kalxas** [comment]
works fine for me

**Comment by kalxas** [comment]
Actually this is how it looks on Firefox:

screenshot_20170831_171655

**Comment by kalxas** [comment]
Same on Chrome:

screenshot_20170831_171918

**Comment by jj0hns0n** [comment]
screen shot 2017-08-31 at 10 57 55
screen shot 2017-08-31 at 10 58 17

**Comment by milafrerichs** [comment]
ok, I'll check the CSS :)

**Comment by Lenninlasd** [comment]
@kalxas I fixed the styles on https://github.com/state-hiu/2C-GeoNode/pull/44

**Comment by kalxas** [comment]
So we close this one and merge #44 ?

**Comment by Lenninlasd** [comment]
yes

**Comment by kalxas** [comment]
Superseded by #75

**Pull request closed without merging**
