### PR TITLE
Add search count for the sepcific text query and the query

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?
Add search count for the sepcific text query and the query

the total results were shown but very small and not that obvious
added it into a directive to lear up the template and add additional testing for text query to it
therefore I needed to copy the search_scripts from geonode master and add the directive.

### Screenshot
bildschirmfoto 2017-08-19 um 15 17 11

### CODE REVIEW

**Comment by kalxas** [comment]
screenshot_20170831_170217

**Comment by jj0hns0n** [comment]
screen shot 2017-08-31 at 10 59 13

We need some kind of a loading/progress indicator here to let the user know its waiting. Perhaps hid the `found` message until the request is fully loaded.

**Comment by Lenninlasd** [comment]
@kalxas @jj0hns0n One question, the layer search has to be in real time while we are writing on the text search?, or the search count text only has to appears when the search has been performed throught the enter keyword or the button search event?

The last case has more sense to me and we can include a loading spinner like:
spinner

**Comment by kalxas** [comment]
Superseded by #75

**Pull request closed without merging**
