### PR TITLE
Full Text Search, Monkeypatching Layer App, Data Provider type filter and Categories in Nav Bar  in 2C GeoNode.

### PR DESCRIPTION
**Pull request by waybarrios**
## ISSUE #28 
- [x] Backend for Layer searching 
- [x] Backend for Document searching 
- [x] Backend for Map searching 
- [x] Frontend  Layer searching 

So, you can search any resources using `'q'` as param in a GET request. 

For example: 

### Layer Search 
`search_query=park`

image

## ISSUE #55
- [x] Monkeypatch For layer app. Adding the following attributes: `dataprovidertype, city, dataprovider_contact, dataprovider_name, dataprovider_url, lineage`

### Monkeypatch Layer App

image

 ## ISSUE #24 & #33 : 

- [x] Add Categories as drop down in main nav bar 
image

## ISSUE #35 
- [x] Add filter for Data Provider Type
image
3o2wxmmzoe

## ISSUE #51 
- [x] Make keywords filtering / faceted search work like CKAN
fqyt4v0bhy

### CODE REVIEW

**Comment by waybarrios** [comment]
this is our PR @kalxas

**Comment by kalxas** [comment]
thanks @waybarrios I will deploy to beta, I am waiting for confirmation on previous features to reach production

**Comment by kalxas** [comment]
We have to fix the api issues (some layers show up 4 times in the search results)

**Comment by waybarrios** [comment]
@kalxas fixed it

**Comment by kalxas** [comment]
Thanks!

**Pull request merged**
