### PR TITLE
Filters and Search text in 2C 

### PR DESCRIPTION
**Pull request by waybarrios**
# What does this PR do?
## Move search bar to the header instead of the sidebar

- Move search bar to header, replicating the CKAN search
- Fix the of the search `HTML/CSS` of the PR https://github.com/state-hiu/2C-GeoNode/pull/27 
All the changes of this PR were included

image

For small devices: 
image

### Related issue: 
https://github.com/state-hiu/2C-GeoNode/issues/26

## Add search count for the specific text query and the query

It was added the search controller in the app in order to show the count message together with spinner the after the search is performed.
dnsunmv0w4

## Adding Filter by Cities
- Issue #30  (Filter by Cities)
image

- Put cites array in Settings file (you can add more cities now) 
```
CITIES = [
    { "name": "Cusco, Peru", "keyword": "Cusco", "image": "/static/img/Cusco3.jpg"},
    { "name": "Denpasar, Indonesia", "keyword": "Denpasar", "image": ""},
    { "keyword": "Douala", "name": "Douala, Cameroon", "image": "/static/img/douala_web4.jpg" },
    { "keyword": "Esmeraldas", "name": "Esmeraldas, Ecuador", "image": "/static/img/esmeraldas_web.jpg" },
    { "keyword": "Kharkiv", "name": "Kharkiv, Ukraine", "image": "/static/img/Kharkiv4.jpg" },
    { "keyword": "Medellin", "name": "Medellin, Colombia", "image": "/static/img/medellin4.jpg" },
    { "keyword": "Merkelle", "name": "Mekelle, Ethiopia", "image": "/static/img/mekelle3.jpg" },
    { "keyword": "Pokhara", "name": "Pokhara, Nepal", "image": "/static/img/pokhara3.jpg" },
    { "keyword": "Port Harcourt", "name": "Port Harcourt, Nigeria", "image": "/static/img/portharcourt_web.jpg" },
    { "keyword": "Santiago", "name": "Santiago, Dominican Republic", "image": "/static/img/santiago_web.jpg" }
]
```
## Disable UPLOAD button
- Disable `UPLOAD_LAYER` button from `Layer_List Url`#76
image

## Upper Search Bar
- Issue #31  (Upper Right Search Bar on Home) It says "Search 2C GeoNode" now.  
image

### CODE REVIEW

**Comment by kalxas** [comment]
another related issue: #76

**Comment by d3netxer** [comment]
Shall we remove the search on the left sidebar next @kalxas ?

**Comment by kalxas** [comment]
yes, that is easy to do.

**Comment by kalxas** [comment]
done @d3netxer

**Pull request merged**
