### PR TITLE
Update settings

### PR DESCRIPTION
**Pull request by milafrerichs**
## What does this PR do?

Update settings according to @simod suggestions.
the TEMPLATES setting would otherwise not work
need to check if this still works in production. @kalxas  
it does work in vagrant and in dev mode

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks @milafrerichs 
I will deploy this PR on our staging VM first before we merge.

**Comment by waybarrios** [comment]
@kalxas it is working?

**Comment by kalxas** [comment]
No, the map composition does not work after this merge.

**Comment by kalxas** [comment]
Superseded from #98

**Pull request closed without merging**
